#!/command/with-contenv bash

conf_dir="/epgd/config"

# make folder
if [ ! -d "$conf_dir" ]; then
    mkdir -p "$conf_dir"
fi

# copy config
if [ -d "$conf_dir" ]; then
    cp --no-clobber --recursive /defaults/config/. "$conf_dir/"
fi

# eMail config (msmtp)
msmtp_conf="/etc/msmtprc"
msmtp_conf_new="$conf_dir/eMail.conf"
if [ -f "$msmtp_conf_new" ]; then
	CONF_COMP="$(cmp --silent $msmtp_conf $msmtp_conf_new; echo $?)"
	if [ $CONF_COMP != "0" ]; then	# only if files are not the same
		echo "Copy new eMail config"
		cp -f "$msmtp_conf_new" "$msmtp_conf"
		chown root:root $msmtp_conf
		chmod 640 $msmtp_conf
	fi
fi
