#!/usr/bin/with-contenv bash

# set timezone

if [ ! -z "$TZ" ]; then
	if [ -f "/usr/share/zoneinfo/$TZ" ]; then
		CURRENT_TZ=$(readlink /etc/localtime)
		if [[ ! $CURRENT_TZ =~ $TZ ]]; then
			unlink /etc/localtime
			ln -s /usr/share/zoneinfo/$TZ /etc/localtime
			echo $TZ >/etc/timezone
			dpkg-reconfigure -f noninteractive tzdata
			echo "Timezone set to: $TZ"
		fi
	elif [ ! -f "/usr/share/zoneinfo/$TZ" ]; then
		echo "Cannot set timezone: $TZ"
	fi
fi
