#!/usr/bin/with-contenv bash

conf_dir="/epgd/config"

# make folder
if [ ! -d $conf_dir ]; then
    mkdir -p $conf_dir
fi

# copy config
if [ -d $conf_dir ]; then
    cp --no-clobber --recursive /defaults/config/. $conf_dir/
fi
