#!/usr/bin/with-contenv bash

conf_dir="/epgd/config"

# make folder
[[ ! -d $conf_dir ]] && \
	mkdir -p $conf_dir

# copy config
[[ -d $conf_dir ]] && \
	cp --no-clobber --recursive /defaults/config/. $conf_dir/

# permissions
chown -R abc:abc /epgd
chmod 755 /usr/bin/svdrpsend
