#!/usr/bin/with-contenv bash

logo_dir="/epgd/channellogos"

# copy logos if dir empty
if [ -z "$(ls -A $logo_dir)" ]; then
	cp --no-clobber --recursive /defaults/channellogos/. $logo_dir/
	echo "YES"
else
	echo "NO"
fi
