#!/usr/bin/with-contenv bash

logo_dir="/epgd/channellogos"

# copy logos if dir empty
if [ -z "$(ls -A $logo_dir)" ]; then
	cp --no-clobber --recursive /defaults/channellogos/. $logo_dir/
elif [ "$LOGO_RECREATE" = "yes" ]; then
	if [ -d "$logo_dir" ]; then
		rm -rf ${logo_dir}/{,.[!.],..?}*
	fi
	cp --recursive /defaults/channellogos/. $logo_dir/
fi
