#!/usr/bin/with-contenv bash

conf_dir="/epgd/channellogos"

# make folder
[[ ! -d $conf_dir ]] && \
	mkdir -p $conf_dir

# copy logos if dir empty
[[ -z "$(ls -A $conf_dir)" ]] && \
	cp --no-clobber --recursive /defaults/channellogos/. $conf_dir/
