#!/usr/bin/with-contenv bash

logo_cp_done="/.logo_cp_done"
logo_dir="/epgd/channellogos"

if [ ! -e "$logo_cp_done" ] && [ "$LOGO_COPY" != "false" ]; then
	echo "Copying new Channellogos to: $logo_dir"
	cp --no-clobber --recursive "/defaults/channellogos/." "$logo_dir/"
	touch "$logo_cp_done"
fi
