#!/usr/bin/with-contenv bash

### !!! this file is also called at finish !!!


## default files and mount points (docker volumes)
declare -a chmown=("/defaults"
		   "/epgd/cache"
		   "/epgd/channellogos"
		   "/epgd/config"
		   "/epgd/epgimages"
		  )

for f in "${chmown[@]}"
do
	echo "Reassign permissions: $f"
	chown -R abc:abc "$f"
	find "$f" -type d -exec chmod 775 {} \;
	find "$f" -type f -exec chmod 664 {} \;
done
